### ISSUE TITLE
Add a watch video call to action next to "Start Free Trial" on the Home page

### ISSUE THREAD

**Issue by lottamus** [stoplightio/stoplight.io#1011]
The Hero component supports multiple call to actions now. Let's add another cta to the home page that opens the video modal: https://github.com/stoplightio/stoplight.io/blob/develop/netlify/pages/home.yaml#L32

TBD on the video

**Comment by ssspear** [comment]
Using this video: https://www.youtube.com/watch?v=iHzFoc4ls8E
