### ISSUE TITLE
Add newsletter signup to the Blog template

### ISSUE THREAD

**Issue by lottamus** [stoplightio/stoplight.io#1012]
We need a way for users to sign up for our blog newsletter. We have a branch with some work already done but I'm not sure where we left off: https://github.com/stoplightio/stoplight.io/tree/feature/SC-110/add-newsletter-signup-to-blog-post

<img width="1676" alt="Prism_v3_Adds_OpenAPI_3_0_and_Goes_Open_Source___Stoplight_API_Corner" src="https://user-images.githubusercontent.com/7423098/61816357-d1db5480-ae11-11e9-8205-318734a1c568.png">

**Comment by ssspear** [comment]
Fixed with #1060
