### ISSUE TITLE
Links to /p should open in a new tab

### ISSUE THREAD

**Issue by lottamus** [stoplightio/stoplight.io#1023]
We're going to be mounting Platform at the path `/p`. In order to render Platform correctly, any links from the static site to `/p` should do a full reload or open in a new tab.

**TODO**
- [ ] add logic to the [link component](https://github.com/stoplightio/stoplight.io/blob/793396e4d04b1ab0b1f9138efc9af6a8c301a260/src/components/Link/index.tsx#L12) that adds `target="_blank"` to `/p` routes

**Comment by collinbachi** [comment]
commenting to subscribe for emails

**Comment by lottamus** [comment]
> commenting to subscribe for emails

Just hit that fancy subscribe button lol

<img width="1542" alt="Banners_and_Alerts_and_Links_to__p_should_open_in_a_new_tab_·_Issue__1023_·_stoplightio_stoplight_io" src="https://user-images.githubusercontent.com/7423098/61914851-9e7af180-af07-11e9-8e75-cb9ead1fd775.png">

**Comment by collinbachi** [comment]
lol I was automatically subscribed but it doesn't email me unless I comment
