### ISSUE TITLE
Redesign Nav Bar

### ISSUE THREAD

**Issue by ssspear** [stoplightio/stoplight.io#1029]
* Use https://www.prisma.io/ as an example
* Remove Sign In Button
* Products, Use Cases, Resources, Open Source, Pricing

<img width="736" alt="Screen Shot 2019-07-30 at 10 51 45 AM" src="https://user-images.githubusercontent.com/33187986/62144817-0b034100-b2b8-11e9-8202-b88c8297b4e6.png">

**Comment by lottamus** [comment]
Fixed by https://github.com/stoplightio/stoplight.io/pull/1098
