### ISSUE TITLE
When I log in with GitHub I can't change my password

### ISSUE THREAD

**Issue by chris-miaskowski** [stoplightio/stoplight.io#1059]
https://dojo-prd.stoplight-dev.com/p/settings/security

![Selection_420.png](https://images.zenhubusercontent.com/5948db0651aa2c3057822fd0/2661fd57-f97a-4a6e-8547-a513bf8d0786)

1. Log in with GitHub
2. Go to account settings, security
3. Try to change password

*expected*

I should not even see that form. I don't have a "previous" password I could use. It is confusing.

*actual*

Form is visible

**Comment by casserni** [comment]
Should be a "Set Password" for instead of a change password form

**Comment by tbarn** [comment]
@chris-miaskowski wrong repo, please move to the correct one.

**Comment by lottamus** [comment]
Issue moved to [stoplightio/app-gen3 #160](https://github.com/stoplightio/app-gen3/issues/160) via [**ZenHub**](https://www.zenhub.com/)
