### ISSUE TITLE
Images show up huge on slow networks

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/stoplight.io#1093]
**Describe the bug**

I've noticed various images flash up on the page whilst loading. On quick networks you'll never see this, but on slower ones (like this Polish ferry) it's rather bad. 

<img width="1402" alt="Screen Shot 2019-08-21 at 10 29 54" src="https://user-images.githubusercontent.com/67381/63416231-5a441980-c3ff-11e9-95a5-e771957fc6a0.png">

**To Reproduce**

1. Be on a polish ferry, or throttle your connection in dev tools
2. Load up the homepage, or any blog page, or a landing page
3. See various images all be the wrong size

**Environment (remove any that are not applicable):**
 - OS: macOS
 - Browser: Firefox 68

**Comment by lottamus** [comment]
@philsturgeon can you check it on https://develop--stoplightio.netlify.com too? Might be fixed with the latest develop

**Comment by philsturgeon** [comment]
Seems so!
