### ISSUE TITLE
Studio Press Release Blog Post

### ISSUE THREAD

**Issue by ksatx** [stoplightio/stoplight.io#1095]
Create a blog post for the Studio Press Release, the same as we did for the Gartner Press Release. Set me as the author.

Needs to go up chronologically before Marc's blog post.

Here is the press release for Studio - https://www.businesswire.com/news/home/20190820005232/en/Stoplight-Launches-API-Visual-Editor-Aimed-Driving

Here is the way we did it for the Gartner Press Release  - https://stoplight.io/blog/gartner-cool-vendor/

**Comment by marbemac** [comment]
Suggestion for the header background image?

**Comment by ksatx** [comment]
![mic large](https://user-images.githubusercontent.com/51092436/63447091-06d2cb00-c401-11e9-9a56-69b4ac3e10c9.jpg
![mic smaller](https://user-images.githubusercontent.com/51092436/63447117-0f2b0600-c401-11e9-8d87-2260bfae0315.jpg)
)

**Comment by marbemac** [comment]
Could you drop the markdown in here when you have a moment?
