### ISSUE TITLE
Marc's Studio Announcement Blog Post

### ISSUE THREAD

**Issue by ksatx** [stoplightio/stoplight.io#1096]
**Chore summary**
Create blog post, Marc set as the author, for Studio announcement. Different from the Press Release Blog post. Needs to go up chronologically after the Press Release blog post. Content for blog post below, link to Google Doc as well.

https://docs.google.com/document/d/1SdR4Sy5OtRtAHpsWD04dDWayE3hoDPxEsqIAlRBfuSM/edit?pli=1#

-------
 
# Stoplight Studio Enables Your API Design Management at Scale
Subtitle: A desktop or web API design experience connected to your own version control system

API tooling is full of walled gardens, with vendors offering solutions for API reference documentation, editors, mocking, code generation, testing, usually all locked up in their own platforms. This makes integration with your own workflows and build pipelines tricky, and means your API descriptions are somewhere other than where they should be: with your code. Stoplight used to work this way, but we're committed to solving this problem.

Today we are sharing the new [Stoplight Studio](https://stoplight.io/studio/), an API design management experience, built with modern development teams in mind. Previous versions of Stoplight required you to keep your API description documents on our servers, but now Stoplight Studio connects to your existing version control! We analyze repos to find relevant files, and give you a beautiful visual editor to make updates or add new information. Then you can commit the changes back to your Git server (GitHub, BitBucket, GitLab, etc).

You also don’t need to convince your entire team to use Stoplight Studio (though we think they’ll come around). We work within your existing file structure, pulling the latest from your OpenAPI, Markdown, and JSON Schema files, as long as they’re committed to a repo we can access. Got a teammate who loves writing YAML in their favorite text editor? No worries, Stoplight Studio can work with that.

We’ll share a lot more about Stoplight Studio over the coming weeks, but here’s a quick look at what is available today:

- Desktop editor experience with offline support
- Built-in support for [Prism](https://stoplight.io/prism/) mock servers on your own machine
- Powerful YAML/JSON linting from [Spectral](https://stoplight.io/spectral/), automatically included
- New web editor interface interoperable with the desktop Studio
- Smooth design-to-docs process to easily share your API functionality

Stoplight Studio is completely free for individuals. We want everyone to have access to the best API design management tooling without compromises or lock-in. For five years, that’s been my goal, and what we’ve built along the way has helped us deliver on that promise.
## First Visual API Designer for API Descriptions
When I founded Stoplight, description formats were getting in the way of API designers. You could use documentation-focused Swagger (which later became OpenAPI) or modeling-centric RAML. In either case, you had to write the YAML or JSON yourself, which caused a barrier to entry for many would-be adopters.

We built the first visual API designer to enable anyone to describe an API without first picking and learning syntax. You could bring an existing document, or start fresh with a builder that walks you through the elements of an API definition. Model request and response data, declare HTTP methods, and field types. Much of this groundbreaking initial interface remains in Stoplight Studio.

Our first API design tool saved valuable developer time and opened up the process to the whole team. Without memorizing formats, enterprise architects and product managers alike could build APIs 10 times faster than using any non-visual editor.
## True OpenAPI Editor Built on Git
When OpenAPI emerged as the industry choice, we wanted our design editor to fully support the format. In 2018, we built the next version to adopt this standard. While our original editor imported and exported multiple API descriptions, it rebuilt the files. That meant we assumed only the standard OpenAPI and anything else, such as extensions, would be lost when rebuilt. Our second visual editor improved upon this flaw and was completely lossless, always providing a view of your OpenAPI document (including any extensions). It also tackled versioning and customizable documentation.

Our customers build and update many APIs, which brings a versioning challenge. We attempted to solve the problem with a tool well known for branching and merging. Our new editor was built atop a hosted Git server, which allowed for tracking revisions and defining versions. We provided a true OpenAPI editor that could go back and forth between a visual editor and the document itself.

Any team member could use the editor, add comments, make updates, and see all the changes. Our customers love the experience and insight it gives them into their API design and development process. Plus, we gave them the tools to share their API beyond the immediate team.

Every API needs documentation, so we created a flexible docs generator from OpenAPI. Though Stoplight Studio supersedes the editor, this documentation tool remains as [Stoplight Hubs](TBD/hubs). Add your own styles, generate API references, and add additional documentation pages. A consumer’s complete experience of your API includes understanding how it works, what is possible, and how to get started. Hubs help you educate developers, whether external or internal while ensuring that documentation is automatically updated along with your OpenAPI document.
## No Compromise API Design Management
Our API design application had solved many of our customer’s problems, but we inadvertently created yet another walled garden. Our own hosted Git repository became the source of truth. Updates to API versions required following our opinionated workflow. And in order to get the maximum benefit, everyone in your organization needed to use our tool.

With Stoplight Studio, our aim is to become part of your workflow, not require you to conform to ours. We connect to your own Git server and bring the lossless OpenAPI visual editor you’ve come to expect. Changes are saved locally until you choose to push them to your repository. We can also detect external changes so you’re always working with the latest version.

In addition to using OpenAPI documents for API design and documentation, we know they’re useful across the API lifecycle. Our team contributes to many open source projects around API tooling, including some we’ve originated ourselves. Two of these are bundled with Stoplight Studio:

- Spectral, a [flexible JSON linter](https://stoplight.io/blog/spectral-v4/), ensures complete OpenAPI definitions and helps your organization design consistent APIs.
- Prism, an [incredibly fast mock server](https://stoplight.io/blog/prism-v3/), can fake your endpoints and data based on OpenAPI documents.

Stoplight Studio is the first of a broader set of tools from Stoplight to help organizations move design-first with their APIs. Collaborate across teams to get feedback—through mock servers, early documentation, and a visual API editor—before you write code. Then make sense of all your API assets at any stage in the lifecycle, right from your own source.

We invite you to [try Stoplight Studio now](https://stoplight.io/studio/). Both desktop and web versions are free. You can open any GitHub URL inside the editor and begin to explore how we interpret your API files. Prototype new endpoints, generate mock servers, or quickly publish documentation. See how Stoplight Studio can provide API design management at scale. No lock-in, no compromises.

**Comment by marbemac** [comment]
Suggestion for the header background image?

**Comment by ksatx** [comment]
Screenshot of Studio

**Comment by ksatx** [comment]
The overarching theme of Studio is collaboration, feedback, and stock images on that theme tend to be really corny/overused. If a screenshot just doesn't look right (I can't really visualize how it will look as the header vs the thumbnail) perhaps something like the attached image 

![group meeting large](https://user-images.githubusercontent.com/51092436/63447486-b871fc00-c401-11e9-800f-3e473bdaeac2.jpg)
