### ISSUE TITLE
Incorrect image renders when sharing links on LinkedIn

### ISSUE THREAD

**Issue by ssspear** [stoplightio/stoplight.io#1114]
**Describe the bug**
Namely's logo is the image that renders 

**To Reproduce**
1. Add a link to an Experience in LinkedIn

**Expected behavior**
As a user, I expect to see an image related to Stoplight, not Namely, when sharing Stoplight's website. 

**Screenshots**
![image](https://user-images.githubusercontent.com/33187986/64047921-bf9db600-cb35-11e9-879f-7ef4bb2a20e1.png)

**Comment by lottamus** [comment]
By "Experience", do you mean "Case Study" or something else?

Either way you can override the image via meta tags:

Here's an example: https://github.com/stoplightio/stoplight.io/blob/6041e80733beb9a63d4da15eb848df900c7c35e4/netlify/pages/home.yaml#L58

Here's where you would want to update the image for that particular post:
https://github.com/stoplightio/stoplight.io/blob/6041e80733beb9a63d4da15eb848df900c7c35e4/netlify/case-studies/namely.md#L33

**Comment by ssspear** [comment]
Closing issue.
