### ISSUE TITLE
Fix stack order of Download Studio sticky button

### ISSUE THREAD

**Issue by ssspear** [stoplightio/stoplight.io#1133]
**Describe the bug**
User is unable to click on all available links due to Download Studio sticky button being the top layer on the page

**To Reproduce**
1. Open https://stoplight.io/design/free/
2. Click on `free API design tooling` link
3. See that nothing happens

**Expected behavior**
User should be able to open `free API design tooling` link

**Screenshots**
![sticky-button](https://user-images.githubusercontent.com/33187986/65443394-9bab5880-ddf3-11e9-9713-6fca94fafef7.gif)

**Additional context**
Sticky has `z-10` so adjusting this ought to do the trick

**Comment by wraybowling** [comment]
I bumped into this today. 
<img width="1665" alt="Screen Shot 2019-10-07 at 4 59 15 PM" src="https://user-images.githubusercontent.com/1120619/66348621-f7fa9600-e924-11e9-9a55-d85d0522880c.png">

**Comment by ksatx** [comment]
Related I believe? Botton stacks on top of videos. 
![download-studio-sticky](https://user-images.githubusercontent.com/51092436/67500658-a5211e00-f648-11e9-9820-c6d70b8c952b.gif)
