### ISSUE TITLE
New Subpage - External/ Public API Documentation

### ISSUE THREAD

**Issue by lottamus** [stoplightio/stoplight.io#1148]
https://storage.3.basecamp.com/3986751/blobs/caf99588-e457-11e9-8db7-ecf4bbd6f9d0/download/Enterprise%20External_Public%20API%20Documentation%20-%20Landing%20Page.docx?attachment=true

**Comment by ksatx** [comment]
Solve by https://github.com/stoplightio/stoplight.io/pull/1174
