### ISSUE TITLE
New Subpage - Internal/ Private API Documentation

### ISSUE THREAD

**Issue by lottamus** [stoplightio/stoplight.io#1149]
https://storage.3.basecamp.com/3986751/blobs/f421d60a-e457-11e9-8886-a0369f740df5/download/Enterprise%20Internal_Private%20API%20Documentation%20-%20Landing%20Page.docx?attachment=true

**Comment by ksatx** [comment]
Solved by https://github.com/stoplightio/stoplight.io/pull/1171
