### ISSUE TITLE
Upload images to Cloudinary or Uploadcare

### ISSUE THREAD

**Issue by ksatx** [stoplightio/stoplight.io#1173]
**Describe the bug**
Can't upload images via Netlify, neither within a template nor via the media section. Attempting to upload an image does not display a confirmation or an error image, but no new media is uploaded.

**To Reproduce**

1. Open https://develop--stoplightio.netlify.com/admin/#/collections/settings
2. Click "Media", media assets box should appear
3. Hit "Upload New"
4. Select any image

**Expected behavior**
Uploading an image should upload to either https://www.netlifycms.org/docs/cloudinary/ or https://www.netlifycms.org/docs/uploadcare/

**Comment by lottamus** [comment]
How large of a file are you trying to upload? Netlify probably has some limits?

![2019-10-24 19 23 00](https://user-images.githubusercontent.com/7423098/67534538-2ce04a00-f694-11e9-8c80-55c12a96136e.gif)

**Comment by ksatx** [comment]
Won't upload for me regardless of size. Tried with several different images, the main one I'm trying to upload is only 10 kb

**Comment by lottamus** [comment]
@ksatx @ssspear can you try it again? Should be fixed now. Please re-open if you run into this again.

**Comment by ksatx** [comment]
It's happening again :/

**Comment by ksatx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Swap Gil with Tim quote Tim Slagle, Developer Advocacy Manager, Zoom "On average, Stoplight saves our team 15-20 hrs per week." Have Link that says, "Watch video"](https://trello.com/c/3qnI43vh/243-swap-gil-with-tim-quote-tim-slagle-developer-advocacy-manager-zoom-on-average-stoplight-saves-our-team-15-20-hrs-per-week-have-l)

**Comment by lottamus** [comment]
Fixed with https://github.com/stoplightio/stoplight.io/pull/1276
