### ISSUE TITLE
RSS/Atom Feeds

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/stoplight.io#1179]
We had a user asking where our blog RSS feed is, and... we dont have one! We should add one, add the meta tags, and add icons to the page, so people can subscribe to get our articles wherever they get their RSS.

**Comment by paulatulis** [comment]
https://github.com/stoplightio/stoplight.io/issues/1179 then https://stoplight-internal.slack.com/archives/C80UQL1EE/p1580925351062100

#1179 RSS/Atom Feeds
We had a user asking where our blog RSS feed is, and... we dont have one! We should add one, add the meta tags, and add icons to the page, so people can subscribe to get our articles wherever they get their RSS.
<https://github.com/stoplightio/stoplight.io|stoplightio/stoplight.io>stoplightio/stoplight.io | Oct 25th, 2019 | Added by GitHub
