### ISSUE TITLE
"CSS Died" 

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/stoplight.io#1189]
A user [on the APIs You Won't Hate Slack](https://app.slack.com/team/UGLTNM0VC) noticed that his CSS was "broken again", and posted this screenshot.

![Screen Shot 2019-10-29 at 3 40 05 PM](https://user-images.githubusercontent.com/67381/67895489-e343a380-fb5a-11e9-8259-a33b9f247b0a.png)

Not sure what the issue is, but maybe this error means something to you.

**Comment by lottamus** [comment]
I believe this is related to https://github.com/stoplightio/stoplight.io/issues/1210
