### ISSUE TITLE
Pre-fill email in request demo form

### ISSUE THREAD

**Issue by lottamus** [stoplightio/stoplight.io#1199]
When a user submits their email on the [enterprise landing page](https://stoplight.io/enterprise/), they are navigated to the [request a demo page](https://stoplight.io/demo/). Since they've just submitted their email, we should pre-populate it in the demo form.

I suggest storing the submitted information from the [Submit component](https://github.com/stoplightio/stoplight.io/blob/develop/src/components/Submit/index.tsx#L27) in [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). You can key the information based on the current page. For example:

```ts
  // Default to existing value in the cache or an empty string
  const defaultValue = window.localStorage.getItem('email') || '';
  const [value, setValue] = React.useState(defaultValue);

  const [loading, response, submitForm] = useSubmitEmailForm(integrations.hubspot, formId);

  const handleSubmit = React.useCallback(
    e => {
      if (e) {
        e.stopPropagation();
        e.preventDefault();
      }

      submitForm([{ name: 'email', value }]);
      // When submitting the form, set the new value in the cache
      window.localStorage.setItem('email', value);
    },
    [submitForm, value],
  );
```

From there, you can set the demo form's email value after it's been loaded [here](https://github.com/stoplightio/stoplight.io/blob/develop/src/components/HubSpotForm/index.tsx#L49) 

```ts
window.hbspt.forms.create({
  target: '#hubspot-form',
  portalId,
  formId,
});

const email = localStorage.getItem('email') || '';
window.hubspot.form.api.getForm(formId).setFieldValue('email', email)
```

Related Trello: https://trello.com/c/lbrpxBwd/249-need-to-have-email-from-enterprise-push-through-to-demo

**Comment by ksatx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Need to have email from /enterprise push through to /demo](https://trello.com/c/lbrpxBwd/249-need-to-have-email-from-enterprise-push-through-to-demo)
