### ISSUE TITLE
Add admin routes to production

### ISSUE THREAD

**Issue by lottamus** [stoplightio/stoplight.io#1204]
We've recently switched over to using master as the default branch. This means the admin portal will create PRs against master and the develop site (https://develop--stoplightio.netlify.com/) will no longer be used.

Currently the admin portal is only [loaded on non-master branches](https://github.com/stoplightio/stoplight.io/blob/e3c2a9059cca5ee1ce70125b26a34e156f136581/src/utils/getRoutes.js#L99). We need to remove that restriction so that admin portal will be up to date with the latest master.

**Comment by philsturgeon** [comment]
Is this fixed here? https://github.com/stoplightio/stoplight.io/pull/1203/files#diff-47c826f0cb4a582591b4ebae434d9e7bL17

**Comment by lottamus** [comment]
> Is this fixed here?

That just targets where the PRs are created from the Admin portal. Also need to include the admin routes in production. But it's not necessary until we make changes to the admin portal code: https://github.com/stoplightio/stoplight.io/blob/e3c2a9059cca5ee1ce70125b26a34e156f136581/src/utils/getRoutes.js#L99
