### ISSUE TITLE
Purge Cloudflare on production deploy

### ISSUE THREAD

**Issue by lottamus** [stoplightio/stoplight.io#1210]
**Chore summary**
We have the Cloudflare CDN sitting in front of our Netlify CDN (weird 🤷‍♂). This causes the Cloudflare cache to become stale whenever we deploy the Netlify site.

There are a few options to fix this:

**Option A**: Add a Netlify [outgoing webhook](https://app.netlify.com/sites/stoplightio/settings/deploys#deploy-notifications) that hits the Cloudflare [purge API](https://api.cloudflare.com/#zone-purge-all-files) on deploy success. Just need to make sure it _only_ does it for production deploys.

**Option B**: Move the marketing site build process to CircleCI, use the [Netlify CLI](https://docs.netlify.com/cli/get-started/#manual-deploys) to do a manual deploy, and hit the Cloudflare [purge API](https://api.cloudflare.com/#zone-purge-all-files). This will give everyone visibility into the build logs which some have been asking for

**Option C**: Add a Cloudflare edge worker that handles routing requests to Platform (/p/*) or the Marketing site (everything else)

cc @collinbachi

**Comment by collinbachi** [comment]
I like option B - it helps standardize our build processes, and gets us out of having to write something to receive and process the netlify webhook

**Comment by lottamus** [comment]
@collinbachi is taking a look at creating a [Cloudflare Edge Worker](https://developers.cloudflare.com/workers/archive/recipes/conditional-routing/) that will handle routing requests to the marketing site (Netlify CDN) and platform

**Comment by XVincentX** [comment]
Maybe this will work?

1. Move the current platform to its own subdomain (`dojo.stoplight.io`, `p.stoplight.io`)
2. Configure our DNS so that `stoplight.io`, `www.stoplight.io` go straight to Netlify
3. Configure the DNS so that p/dojo go to our infrastructure/clodflare
4. Do a netlify redirect from `stoplight/p` to `dojo.stoplight.io`
5. Profit

This should not affect any on-premise installation nor having repercussions on the on premise installations

@marbemac @collinbachi @lottamus

**Comment by collinbachi** [comment]
@XVincentX that will definitely work and is how it was done for Next, but we'd be sacrificing serious style points.

**Comment by collinbachi** [comment]
Results from testing with Cloudflare Workers, VA=virginia, FF=frankfurt, all units in seconds:
.34 VA-->cloudflare-->nginx-->netlify
.18 VA --> netlify
.28 VA-->cloudflare worker-->netlify

.4 FF-->cloudflare-->nginx-->netlify
.15 FF --> netlify
.26 FF --> cloudflare worker-->netlify

Note that the current stoplight.io setup, utilizing the cloudflare cache, is consistently under .1s--even faster than netlify CDN. I'll leave it to others to decide if the cloudflare worker latency is acceptable.

**Comment by collinbachi** [comment]
(the cloudflare worker does work as we hoped for edge routing, good call @lottamus)

**Comment by XVincentX** [comment]
What is a style point?

Enviado do meu iPhone

**Comment by lottamus** [comment]
@collinbachi are we using the Cloudflare Workers now? If so, can we close this issue?

**Comment by collinbachi** [comment]
stoplight.io is now behind a cloudflare worker that routes traffic towards the marketing site or platform depending on the path
