### ISSUE TITLE
Improve /about page

### ISSUE THREAD

**Issue by lottamus** [stoplightio/stoplight.io#1234]
**User story.**
As a user, I can do view the /about page, so that I can learn about the Stoplight team, mission, core values, etc.

**Describe the solution you'd like**

- [x] Add a section for our mission statement
- [x] Add a section for our core values
- [ ] Add a section for where we're located across the globe (?)
- [ ] Add a section for conference's we're attending (?)
- [ ] Add a section for Offsite Earth project (?)
- [ ] Add a section for the [open jobs widget](https://id.workable.com/oidc/i/6d36ab82-e2af-4f17-a0e2-9c0b062f12c6)

**Additional context**
- Algolia is an example of a good about page: https://www.algolia.com/about/
- Growth Trello card: https://trello.com/c/x2ousw22/252-improve-about-us

**Comment by ksatx** [comment]
@paulatulis I've done some thinking on this a bit already and have some blurbs put together for it, if you want put heads together next week. 

Including the HTML for one of our Offset Earth badges below (there are 8 variations, landscape, portrait, dynamic, static, dark, light).

<a href="https://offset.earth/stoplightinc" target="_blank" rel="noopener noreferrer" title="View our Offset Earth profile" style="width:200px;display:inline-block;">
  <img alt="We offset our carbon footprint via Offset Earth" src="https://toolkit.offset.earth/carbonpositiveworkforce/badge/5db9f5263b387200179a1d3d?black=true&landscape=true" style="width:200px;" />
</a>

**Comment by paulatulis** [comment]
Yes! Sounds wonderful - let's do it.

**Comment by ksatx** [comment]
"In 2014, Marc MacLeod worked as an independent software consultant in Los Angeles building Application Programming Interfaces, known as APIs, for companies. MacLeod noticed that many of the APIs, which are systems of tools and resources in an operating system that enable developers to create software applications, lacked documentation and were poorly built. So, MacLeod created a set of tools to serve as a blueprint for how to build better APIs, and those tools became the foundation behind Stoplight."

"Stoplight’s mission is to enable all stakeholders working with APIs to be more productive. We believe in a design-first approach to API development, so we created products that provide a means for design-first development. Developing good design-first practices will minimize future costs, speed up your time to market and lead to more consistent, higher quality microservice and IoT applications."

"Companies have hundreds of thousands of APIs – most built without clear documentation or adherence to any kind of standard. Stoplight offers a suite of tools for stakeholders to ensure that their API is built uniformly and correctly to the company’s standards. The platform automates all kinds of tasks for software developers and provides a project management collaboration workplace for distributed teams to work on a project."

"Headquartered in Austin, Texas, our team hails from across the US and Europe, and is united by our passion for APIs. From skeeball champions to rock climbers, tough mudders to restaurateurs, each and every member brings their own unique perspectives and experiences to the table. Thinking out of the box is our purpose - the weirder the better - and challenging the status quo is our culture."

**Comment by ksatx** [comment]
Career Plug in use example [](https://www.freightpros.com/careers/)

**Comment by ksatx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SEO suggested changes for home page](https://trello.com/c/0H41FIIi/269-seo-suggested-changes-for-home-page)

**Comment by ksatx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve /about-us](https://trello.com/c/x2ousw22/252-improve-about-us)

**Comment by paulatulis** [comment]
How do we feel about mimicking our product landing pages? 

Having the anchor links and corresponding feature strip allows us to add/remove sections pretty easily, so as we have a solidified mission statement, values, etc, we can update accordingly. 


![Screenshot 2019-11-14 at 12.39.50 PM.png](https://images.zenhubusercontent.com/5dc060647a4d02000177a6d0/402c3fe8-d12f-426c-bb50-61e537d29297)

**Comment by ksatx** [comment]
I think it's a great idea!

**Comment by paulatulis** [comment]
@ksatx @lottamus is there anywhere I could find additional team photos? If we want to go with the feature style, we'll need to fill in those circular sections with related images. Happy to talk through in person tomorrow!

**Comment by ksatx** [comment]
For history, maybe we can use a screenshot of [this press release](https://www.prweb.com/releases/2016/02/prweb13215787.htm)? Marc might have some pictures from Tech Stars, I'll check with him next week.
![axes3](https://user-images.githubusercontent.com/51092436/68978740-3eaf9b80-07c1-11ea-9367-c4d00007ffd3.jpg)
![axes2](https://user-images.githubusercontent.com/51092436/68978741-3f483200-07c1-11ea-9e7d-10a17e1fd278.jpg)
![axes](https://user-images.githubusercontent.com/51092436/68978742-40795f00-07c1-11ea-8ab7-f40d3263a35a.jpg)
![groupaxes](https://user-images.githubusercontent.com/51092436/68978836-86362780-07c1-11ea-8256-9b3e868b82ba.jpg)
![old group pic](https://user-images.githubusercontent.com/51092436/68978840-8a624500-07c1-11ea-996b-61a985ee2fb8.jpg)

**Comment by ksatx** [comment]
![swagless](https://user-images.githubusercontent.com/51092436/68979411-1628a100-07c3-11ea-8018-024b75789085.jpg)

**Comment by ksatx** [comment]
![climate-positive-workforce-black-landscape](https://user-images.githubusercontent.com/51092436/69069556-48691700-09ec-11ea-8fdd-dbb89996fdb4.png)
![climate-positive-workforce-black-portrait](https://user-images.githubusercontent.com/51092436/69069563-4c953480-09ec-11ea-9d59-05ee34c66834.png)
