### ISSUE TITLE
Add links to design, docs, and mocking on the home page

### ISSUE THREAD

**Issue by lottamus** [stoplightio/stoplight.io#1237]
Add a new section above the ["STOPLIGHT POWERS SOME OF THE WORLDS LEADING API FIRST COMPANIES"](https://github.com/stoplightio/stoplight.io/blob/6041e80733beb9a63d4da15eb848df900c7c35e4/src/templates/Home/index.tsx#L28)

Title: "Stoplight covers all the use-cases for the API lifecycle"
Divider color: "blue"

Add 3 Cards like the ones here: https://web.archive.org/web/20180823165038/https://stoplight.io/
- "API Designer" links to https://stoplight.io/design/
- "Hosted Docs" links to https://stoplight.io/documentation/
- "Mocking" (Prism) links to https://stoplight.io/mocking/

For the cards, you can use the same component as the case studies here: https://github.com/stoplightio/stoplight.io/blob/a29d880810ed850b5b426f02d54e71af67be5b3a/src/components/CustomerSection/index.tsx#L96

Relevant Trello card: https://trello.com/c/0H41FIIi/269-seo-suggested-changes-for-home-page

**Comment by ksatx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SEO suggested changes for home page](https://trello.com/c/0H41FIIi/269-seo-suggested-changes-for-home-page)
