### ISSUE TITLE
Can't save changes to /pricing from admin portal

### ISSUE THREAD

**Issue by ksatx** [stoplightio/stoplight.io#1247]
**Describe the bug**
Cannot save changes to /pricing via admin portal. Attempting to save changes flags path as required field. When path is filled in with /pricing, changes don't save but no error message appears either. Error message was displaying last week, but I didn't take a screenshot and I've slept since then so I can't swear to what it said. 

**To Reproduce**

1.  Go to [https://stoplight.io/_admin/#/collections/pages/entries/pricing](https://stoplight.io/_admin/#/collections/pages/entries/pricing)
2. Make any change - in this case, I'm trying to set Robots to no index, no follow under the Meta.

**Expected behavior**
1. "Path" is flagged as required field, changes don't save.
2. When "path" is filled in with the current existing path, /pricing, required field flag disappears but changes do not save.
3. No other error message appears.

**Comment by lottamus** [comment]
We've commented out the `/pricing` page in an attempt to hide that page even though it is still being rendered (thats another issue): https://github.com/stoplightio/stoplight.io/commit/68f1176c13814d10c83a0a75c49de81ee440d646#diff-0040a661df2812e51361320553daa5f2R1

What are you trying to update? And do we even want to update this pricing page? I was under the assumption that we wanted to hide it and direct people to https://stoplight.io/hubs/#pricing

**Comment by ksatx** [comment]
You're correct, we want to hide it. I'm trying to update the meta to no index, no follow so we get less traffic there via organic.

**Comment by lottamus** [comment]
I added back the path and added "noindex, follow" meta tags
