### ISSUE TITLE
Update /prism to highlight some new features in v3.2

### ISSUE THREAD

**Issue by lottamus** [stoplightio/stoplight.io#1269]
https://github.com/stoplightio/prism/blob/master/CHANGELOG.md

Need to sync with @XVincentX to find out exactly what we want to add

**Comment by XVincentX** [comment]
@paulatulis @lottamus 

Here's what I'd highlight:

* Support for callbacks for OpenAPI 3.0 documents
* Support for all the security specifications
* Proxy command to an upstream server with response validation

**Comment by paulatulis** [comment]
@XVincentX  let me know when you are free to connect about this this week.
