### ISSUE TITLE
Add Core Values to /about

### ISSUE THREAD

**Issue by ksatx** [stoplightio/stoplight.io#1286]
**Chore summary**
Add Core Values to /about page when they are finalized.

**Comment by ksatx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Second round of improvements to /about](https://trello.com/c/x4dGaUvs/309-second-round-of-improvements-to-about)

**Comment by paulatulis** [comment]
@ksatx let me know if you want me to take care of this real quick/ we can go over together.

**Comment by lottamus** [comment]
@paulatulis did you get the core value descriptions from the all hands slides?

**Comment by paulatulis** [comment]
@lottamus yes I did! Will update this by EOD.
