### ISSUE TITLE
Catalog and Extract common components

### ISSUE THREAD

**Issue by lottamus** [stoplightio/stoplight.io#1287]
**Chore summary**

As discussed in the growth meeting, there are several components that are not "easily re-useable". I suggest we catalog all the components we have and the ones that are not easily re-used into separate lists on this issue. Once we finish this task, we can then decide what "new" components we will need to build.

**Tasks**

- [ ] Look at the src/components folder to make a list of what's in there and decide if they're easy to use
- [ ] Look at the src/templates folder and make a list of components that should be extracted to the common src/components folder

**List of common components**

- Component Name: description of the component

**List of components in the templates folder that should be extracted to common components**

- Template Name: description of the component in the template that should be extracted

**Comment by paulatulis** [comment]
@lottamus 

[Google Doc for every component with notes](https://docs.google.com/spreadsheets/d/1B64ywn5hJL_BQ58BQl5ny8s-02Q6zzELp2tc-X0S77E/edit?usp=sharing)

Let me know if this looks like the right direction/if anything big is missing, etc.

**Comment by lottamus** [comment]
@paulatulis looks good so far! Do you want to meet on it tomorrow?

**Comment by paulatulis** [comment]
@lottamus Absolutely
