### ISSUE TITLE
Add photo attribution

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/stoplight.io#1314]
Add attribution for the hero photo here:

https://stoplight.io/blog/studio-press-release/

Something like:

"Photo by Gavin Whitner (https://www.flickr.com/photos/156466858@N02/49398518677/)"

**Comment by ksatx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Photo Cred](https://trello.com/c/9dIgILUg/327-update-photo-cred)
