### ISSUE TITLE
Blog jumps to bottom of post when loading

### ISSUE THREAD

**Issue by ksatx** [stoplightio/stoplight.io#1361]
**Describe the bug**
When you click on a blog post, the page loads slowly and jumps to the bottom of the markdown body before it completely renders

**Screenshots**
https://stoplight-internal.slack.com/archives/C80UQL1EE/p1581439168071400

**Comment by paulatulis** [comment]
@philsturgeon @ksatx I'm unable to reproduce this in any browser. Is this still happening for you?

**Comment by philsturgeon** [comment]
Yeah it's still happening. I just go to stoplight.io, click Blog, then click the top post. It goes right to # Thanks

**Comment by ksatx** [comment]
@paulatulis It doesn't happen to me every time, but it does happen pretty frequently. I can't figure out how to reproduce it consistently.
