### ISSUE TITLE
GitHub organisation repo 403 error

### ISSUE THREAD

**Issue by johnfg10** [stoplightio/stoplight.io#1380]
**Describe the bug**
When pushing changes to a github repo thats owned by a organisation stoplight returns a 403 error. I tested on a personally owned repo which worked as expected

**To Reproduce**
1. Create github organisation
2. Create empty repo in said organisation
3. import in the stoplight tool
4. add a API to the project
5. Commit it to github
6. See error stated below

**Expected behavior**
I expected the changed made to be pushed to the app to be pushed to the github repo

**Screenshots**
![image](https://user-images.githubusercontent.com/5445550/74675782-385c0180-51ac-11ea-9524-b4a8a2596d5f.png)

**Environment (remove any that are not applicable):**
 - OS: Windows 10
 - Browser: Microsoft edge
 - Version: Web

**Comment by johnfg10** [comment]
log from console: Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)

**Comment by johnfg10** [comment]
had to enable organisation access manually in github. might be worth adding something in the docs? il leave this open for now

**Comment by paulatulis** [comment]
Hi @johnfg10 

Thanks for flagging this! Can you please reach out directly to support@stoplight.io ? Our support team will be happy to assist. 

- Paula

**Comment by brandonjmckay** [comment]
Having this same issue.
Not sure I follow the steps to fix this based on the conversation here

**Comment by johnfg10** [comment]
so if you go to settings>applications>Stoplight then grant access to all of the organisations listed should solve it

**Comment by brandonjmckay** [comment]
I think I found it under that sections' oauth apps, looks like I need to request access for it from my company org.
Hopefully that unblocks me, thanks for the help @johnfg10 !
