### ISSUE TITLE
Create/Update Docs (Hubs?) landing page

### ISSUE THREAD

**Issue by paulatulis** [stoplightio/stoplight.io#1395]
Ahead of V2, we need to make marketing site updates. Instead of the Product dropdown, we will have a Solutions Dropdown with all of our solutions.

- Design
- Docs (Hubs?)
- Mocking
- Visibility
- Quality
- Consistency
- Technical Knowledge Base

Notes: can we use the current /docs page?

**Comment by paulatulis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create/Update Docs (Hubs?) landing page](https://trello.com/c/u0xIGRjh/389-create-update-docs-hubs-landing-page)

**Comment by ksatx** [comment]
Like we touched on this, 'Docs' reads as public documentation, and sales are pretty adamant about moving away from 'Hubs' terminology which is a good idea in my book. If we think about this a solutions page and not a product page necessarily I think /docs is sufficient on its own, and then we can get granular with features on /pricing? 

_Flavors of Docs to Keep in Mind_

- Free Docs (currently featured on /docs)
- Paid Docs (current /docs offering + Custom Domains, Theming, and Login-Protected docs)
- Free Elements (embeddable widgets branded with Powered by Stoplight)
- Paid Elements (Whitelabel widgets)
