### ISSUE TITLE
Incorrect generation of example types

### ISSUE THREAD

**Issue by johnfg10** [stoplightio/stoplight.io#1430]
**Describe the bug**
When you are using stoplight and create a example for a given field, stoplight auto generates all fields as string rather then deferring to the field type thats defined

**To Reproduce**
1. https://gist.github.com/johnfg10/fc566ef579a156db47753fb508e4fffb
you will notice if you change the example field it inserts it in quotes rather then a standard int then shows a error pointing this out, which you then need to change by hand

**Expected behavior**
https://gist.github.com/johnfg10/5b0ff2c7479230e46af3bddb2f311e54
The expected example would use a int

**Environment (remove any that are not applicable):**
 - Stoplight version: 1.10.2
 - OS: Windows 10(installed via electron)

**Comment by philsturgeon** [comment]
@johnfg10 oh hey, sorry for the delay john I didn't notice this over here. This is the marketing site, trouble with studio is usually reported over here: https://github.com/stoplightio/studio

Great news though, this specific issue was solved already: https://github.com/stoplightio/studio/issues/349
