### ISSUE TITLE
chore: add image component to /enterprise template

### ISSUE THREAD

**Issue by ksatx** [stoplightio/stoplight.io#1451]
**Chore summary**
Support full-width images in the body of /enterprise
![illustration-on-enterprise](https://user-images.githubusercontent.com/51092436/81618118-56509100-93ac-11ea-9126-54e24cca1bf5.gif)

**Comment by ksatx** [comment]
@paulatulis sorry about the complete lack of information in this issue, the doggies were howling for their dinner. 

We want to be able to put a full-width image on the enterprise page underneath the little feature icon section.

**Comment by paulatulis** [comment]
@ksatx so sorry for the delay on this! Can you send me that placeholder image so I can make sure the dimensions look okay?

**Comment by ksatx** [comment]
![output-for-enterprise](https://user-images.githubusercontent.com/51092436/82362757-71398b80-99d2-11ea-96d0-1c38774d170c.png)

**Comment by ksatx** [comment]
Fixed with #1436
