### ISSUE TITLE
Site styling chores

### ISSUE THREAD

**Issue by ksatx** [stoplightio/stoplight.io#1472]
To Do's for #1467

**Outstanding Blocker**
- [x] Executive direction on design and theme - how to reconcile current version with the branding proposed by Spoke, attached below

**Styling Chores**
- [x] Move Spectral sandbox out of hero and into the first full-width feature section.
- [x] Ability to add href to Testimonials or Quotes component
- [ ] Fixing hover styling on buttons, so that '{color}-lightest,-lighter, light, dark, darker, darkest' are hover responsive as well. 
- [x] resolve font-color on blog post title and subtitle 
- [x] resolve nav bar background on blog posts before scroll  
- [ ] make sure font styling is consistent throughout

**Other things to do, waiting on executive design direction**
- [x] figure out consistent use of particles - /enterprise/ /pricing/ /blog/ /video/ all have particles and look pretty OK, but particles would look odd on the homepage as it is. Should we remove altogether?
- [x] Resolve styling on tabbed pages like /blog and /api-types - if the hero is white, the tabs are invisible. If the tabs are colored without a bottom border or anchor bar, they look like weird floating blocks. If the hero is a color, like on /api-types, the header and logo lose contrast. 
- [ ] make sure CTA styling is consistent throughout the site, with the same primary, secondary, and tertiary colors
- [x] Add border radius to tab bar
- [x] Add margin between top list item and the bottom of the tab bar (like a blog post)

![image11](https://user-images.githubusercontent.com/51092436/84538110-b2157f00-acb6-11ea-876d-25bae9cc2461.png)

**Comment by paulatulis** [comment]
Ability to add href to Testimonials or Quotes component 
^^ if we do this and they aren't all hyperlinked, the ones without hyperlinks could appear to be broken. Right now I have links to case studies for everything on [this page](https://stoplight.io/case-studies/) so we just want to make sure the testimonials match. Let me know what we want to swap out JumpCloud for - or let me know if there's a different link.

**Comment by ksatx** [comment]
> Ability to add href to Testimonials or Quotes component
> ^^ if we do this and they aren't all hyperlinked, the ones without hyperlinks could appear to be broken. Right now I have links to case studies for everything on [this page](https://stoplight.io/case-studies/) so we just want to make sure the testimonials match. Let me know what we want to swap out JumpCloud for - or let me know if there's a different link.

We can hyperlink all of them. We just need to keep the internal links to SEO pages (/design /documentation /mocking) on the homepage, without them being displayed so prominently.
