### ISSUE TITLE
only top half of Tabs are clickable?

### ISSUE THREAD

**Issue by wmhilton** [stoplightio/stoplight.io#1492]
## Describe the bug

Only the top half of Tabs are clickable on pages like https://stoplight.io/openapi/design/and https://stoplight.io/api-design-guide/basics/

## To Reproduce

![2020-06-25 13 33 27](https://user-images.githubusercontent.com/587740/85770148-9c597e00-b6e8-11ea-8dc7-62d3e9781e3c.gif)

## Theory

If you right-click and inspect element, you can see that the `markdown-body` div is partially covering the tabs. So it's probably a padding or margin or z-index thing, not a JavaScript thing.

![2020-06-25 13 35 35](https://user-images.githubusercontent.com/587740/85770473-f22e2600-b6e8-11ea-98e0-e48a78e30f0b.gif)

## Expected behavior

Ought to be able to click & hover anywhere on a tab yeah.

## Additional context
Squeeeeee the website is so beautiful.

**Screenshots**

**Environment (remove any that are not applicable):**
 - OS: macOS 10.15.5
 - Browser: Chrome 83 and Firefox 77.0.1 (64-bit)

**Comment by paulatulis** [comment]
fixed with https://github.com/stoplightio/stoplight.io/pull/1500
