### ISSUE TITLE
Should "Read the announcement" banner be present on the actual announcement?

### ISSUE THREAD

**Issue by filipebarcos** [stoplightio/stoplight.io#1493]
Not a huge deal, but do we want this behaviour?
![image](https://user-images.githubusercontent.com/303141/85771627-7b962600-b6f2-11ea-81ea-208aa5391bd9.png)

Present on: https://stoplight.io/blog/stoplight-platform/

**Comment by paulatulis** [comment]
Thanks for flagging this! 
fixed with https://github.com/stoplightio/stoplight.io/pull/1494
