### ISSUE TITLE
chore/ noindex netlify admin

### ISSUE THREAD

**Issue by texas-kristen** [stoplightio/stoplight.io#1501]
## Summary

The XML sitemap currently links to the CMS page  https://stoplight.io/_admin/. This has the same meta title as the homepage, which can potentially cause cannibalization if search engines start to index it. 

[ACTION]
The URL ( https://stoplight.io/_admin/ ) should be removed from the XML sitemap, and the URL should also have the following meta robots tag:
 <meta name="robots" content="noindex"/> 

Add any other context about the chore here.
![image](https://user-images.githubusercontent.com/51092436/85872351-36770000-b795-11ea-83ef-b88f22d54f65.png)

**Comment by paulatulis** [comment]
stoplight.io/_admin is no longer showing in the xml 

<img width="1422" alt="Screen Shot 2020-06-26 at 1 55 35 PM" src="https://user-images.githubusercontent.com/47359669/85891556-e9a32180-b7b4-11ea-9cfc-62a1bb305d5a.png">


still looking into the noindex issue
