### ISSUE TITLE
bug/banner doesn't close

### ISSUE THREAD

**Issue by texas-kristen** [stoplightio/stoplight.io#1517]
## Describe the bug

Banner does not close when the z is clicked

## To Reproduce

1. Go to any page on stoplight.io
2. Click the X to close the banner

## Expected behavior

After fix, the banner should close when the x is clicked

**Environment:**
 - OS: Windows 10
 - Browser: Version 83.0.4103.116 (Official Build) (64-bit)

**Screenshots**

![banner_bug](https://user-images.githubusercontent.com/51092436/87176202-664afb00-c29f-11ea-80f1-6c41db8285e6.gif)

**Comment by paulatulis** [comment]
https://github.com/stoplightio/stoplight.io/pull/1519
