### ISSUE TITLE
Cannot import GitHub repository

### ISSUE THREAD

**Issue by fedecastelli** [stoplightio/stoplight.io#1520]
I've to update the Swagger documentation using this product. The company that wants to update the documentation added me as a collaborator of the repository and not of the organization. I clicked on the `+` -> `GitHub Integrations` and I accepted the GitHub App. The problem is that I can see only all the organizations and not direct repositories.

Am I doing something wrong? If everything is correct, could it be considered as a feature request?

**Comment by philsturgeon** [comment]
Hey @fedecastelli. Sorry we didn't spot this until now, this is the repo for the marketing site and we don't usually monitor it so closely. 

This [documentation for adding projects](https://meta.stoplight.io/docs/platform/2.-workspaces/b.adding-projects.md) should help! If not, click the Support button to speak with somebody who can help you further!

<img width="616" alt="image" src="https://user-images.githubusercontent.com/67381/88306040-83091900-cd0a-11ea-86f5-e2d7f9d97b2a.png">
