### ISSUE TITLE
Images are over-compressed

### ISSUE THREAD

**Issue by marbemac** [stoplightio/stoplight.io#974]
Settings here: https://github.com/stoplightio/stoplight.io/blob/9df32e54390a6a1c4c08edaa9895f5bb6bb9d839/src/utils/processImages.js#L9-L14

Suggest we target width rather than height, and remember that should be a little less than double whatever max width we are looking for (for retina screens). 

Large should target the width of the site container (which should also be increased to 1250px or so imho). So that would mean large = ~2000px. The other sizes should be adjusted accordingly as well.

**Comment by lottamus** [comment]
This should be as simple as just changing those values in the config and updating the image component to use width instead of height

Another option is using Netlify's large media service: https://www.netlify.com/docs/large-media/

**Comment by marbemac** [comment]
I think we can actually remove all compression now that we're running the traffic through cloudflare, which has built in on the fly image compression. Thoughts @lottamus @ssspear?

**Comment by lottamus** [comment]
Closing in favor of Cloudflare's image optimization
