### ISSUE TITLE
Cannot scroll Monaco in FireFox using scroll-wheel/trackpad

### ISSUE THREAD

**Issue by lottamus** [stoplightio/stoplight.io#991]
**Describe the bug**

Unable to scroll the Monaco Editor when using FireFox.

**To Reproduce**

1. Open FireFox to https://stoplight.io/spectral
2. Attempt to scroll the MonacoEditor using your trackpad.
3. Notice FireFox scrolls the page instead.

**Screenshots**

**Environment (remove any that are not applicable):**
 - Browser: FireFox

**Additional context**

- https://github.com/Microsoft/monaco-editor/issues/1353

**Comment by ksatx** [comment]
@paulatulis not sure if this is still happening, it looks okay to me but would you mind double checking before closing?

**Comment by paulatulis** [comment]
We're not currently using this. Closing for now.
